# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: agent-1

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build || echo "No build script found, skipping"

  ecr:
    name:  Build & Push Docker Image to ECR
    needs: build 
    runs-on: agent-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password | docker login \
            --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

          docker build -t $REPO_URI:$IMAGE_TAG .
          docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

      - name: Push Image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

          docker push $REPO_URI:$IMAGE_TAG
          docker push $REPO_URI:latest
        
        
