name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: agent-1

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build || echo "No build script found, skipping"

  ecr:
    name:  Build & Push Docker Image to ECR
    needs: build 
    runs-on: agent-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS using IAM Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password | docker login \
            --username AWS \
            --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Set Repository URI
        id: set_uri
        run: |
          echo "repo_uri=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ steps.set_uri.outputs.repo_uri }}:$IMAGE_TAG .
          docker tag ${{ steps.set_uri.outputs.repo_uri }}:$IMAGE_TAG ${{ steps.set_uri.outputs.repo_uri }}:latest

      - name: Push Image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ${{ steps.set_uri.outputs.repo_uri }}:$IMAGE_TAG
          docker push ${{ steps.set_uri.outputs.repo_uri }}:latest
        
        
